include $(THEOS)/makefiles/common.mk

TWEAK_NAME = HSSPrefs
HSSPrefs_FILES = HSSPrefs.xm SiriApplicationListController.xm 
HSSPrefs_LIBRARIES = applist
HSSPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/tweak.mk
